### ISSUE TITLE
Doesn't compile with geometrize-haxe 1.0.2

### ISSUE THREAD

**Issue by mastef** [Tw1ddle/geometrize-haxe-web#2]
```
GeometrizeWorker.hx:17: characters 7-22 : Type not found : geometrize.Util
```

**Comment by mastef** [comment]
Ah went around this by using `git submodule update --init --recursive`

**Comment by Tw1ddle** [comment]
It uses the submodule by default. Uncomment line in `GeometrizeHaxeWeb.hxml` to use haxelib instead. The 1.0.2 haxelib is working for me.
